services:
    open-webui:
        image: ghcr.io/open-webui/open-webui:main
        container_name: open-webui
        restart: unless-stopped
        environment:
            - OLLAMA_BASE_URL=http://192.168.1.181:8000/v1
        volumes:
            - open-webui:/app/backend/datahttp://192.168.1.181:8000/v1
        ports:
            - "${OPEN_WEBUI_PORT}:8080"   
   
   qdrant:
        image: qdrant/qdrant:latest
        container_name: qdrant
        restart: unless-stopped
        environment:
            - QDRANT__TELEMETRY_DISABLED=true
            - QDRANT__LOG_LEVEL=INFO
        volumes:
            - ${DATA_SSD}/qdrant_data:/qdrant/storage
        ports:
            - ${QDRANT_HTTP_PORT}:6333
            - ${QDRANT_GRPC_PORT}:6334
        configs:
            - source: qdrant_config
              target: /qdrant/config/production.yaml

configs:
    qdrant_config:
        content: |
            cluster:
                enabled: false
            service:
                enable_cors: true

networks:
    default:
        external: true
        name: ${NETWORK_NAME}      