services:
    portainer:
        image: portainer/portainer-ce:sts
        container_name: portainer
        restart: unless-stopped
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data_local:/data
            - ${CONF_SSD}/portainer/portainer_password.txt:/tmp/portainer_password.txt:ro
        ports:
            - ${PORTAINER_PORT}:9443
        command: 
            --admin-password-file '/tmp/portainer_password.txt'

networks:
    default:
        external: true
        name: ${NETWORK_NAME}

volumes:
    portainer_data_local:
        name: portainer_data_local