services:
    sabnzbd:
        image: lscr.io/linuxserver/sabnzbd:latest
        container_name: sabnzbd
        restart: unless-stopped
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${CONF_SSD}/sabnzbd:/config
            - ${DATA_SSD}/downloads:/downloads
            - ${DATA_SSD}/downloads/incomplete:/incomplete-downloads
        ports:
            - 8181:8080

networks:
    default:
        external: true
        name: ${NETWORK_NAME}